### ISSUE TITLE
Add --extra-index-url note to Readme

### ISSUE THREAD

**Issue by davidiwharper** [ddh0/easy-llama#5]
Thanks for your work on this page, it's looking good.

Could you please consider whether to add a note about using the precompiled cpu, cuda, and metal repositories for installation? This seems quite in keeping with the ethos of making things as easy as possible.

At present [there is a bug which is making this command a little harder](https://github.com/abetlen/llama-cpp-python/issues/1684) (one has to specify the prior version), but in general the easier install command is:

`pip install llama-cpp-python --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cpu # for non-accelerated`

`pip install llama-cpp-python --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/metal # osx`

`pip install llama-cpp-python --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu122 # cuda, in this instance 12.2`

CUDA 12.1-12.4 is currently supported.

To check the CUDA version on Windows or Linux:
`nvcc --version`

I hope this is helpful ;)

**Comment by ddh0** [comment]
Hi! Sorry for the delayed response.

For the time being I'm going to stick with doing the compilation at installation time. The reason is that compiling llama.cpp on the target device will enable all the processor-and architecture-specific optimizations per [the llama.cpp Makefile](https://github.com/ggerganov/llama.cpp/blob/master/Makefile).

However I am aware that the current installation instructions are kind of awkward, and they require `cmake` to be installed. I'll add a note to the README soon mentioning the commands you've provided.

Thank you!
