### ISSUE TITLE
Corrections in formats.py

### ISSUE THREAD

**Issue by iwr-redmond** [ddh0/easy-llama#7]
A few minor corrections:

1. alpaca listed twice, L98 and L187
2. solar_instruct system_prefix (L410) should be "### System:", per the [tokenizer settings](https://huggingface.co/upstage/SOLAR-10.7B-Instruct-v1.0/blob/main/tokenizer_config.json).

**Comment by ddh0** [comment]
Hey, thanks for this. :)

Coincidentally I actually just re-did the whole formats module just before I saw this issue. In the process I seem to have gotten rid of the duplicate alpaca format, because I can't find any duplicates.

As for the solar_instruct system prefix, it looks like it should be `### System:\n` based on what I'm seeing:
<img width="624" alt="Screenshot 2024-11-17 at 10 27 15 PM" src="https://github.com/user-attachments/assets/d594e967-4fda-4d1a-83bb-26bd7c86dc44">
